### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [fi-muni/PA165#46]
Hi
The following lines have cryptographic API misuses. <br> File name => eshop-service/src/main/java/cz/fi/muni/pa165/service/UserServiceImpl.java: Line number => 72: API name => PBEKeySpec:<BR> File name => eshop-service/src/main/java/cz/fi/muni/pa165/service/UserServiceImpl.java: Line number => 72: API name => PBEKeySpec:Operation on object of type javax.crypto.spec.PBEKeySpec object not completed. Expected call to clearPassword<BR>

**Comment by martin-kuba** [comment]
Closing as spam, see https://github.com/mob41/broadlink-java-api/issues/22
