### ISSUE TITLE
Implement REST API

### ISSUE THREAD

**Issue by minicuts** [fi-muni/PA165#5]
If possible, shortly describe REST API architecture here https://docs.google.com/document/d/14PboCcH8nltP8KBVJaXrFcugHF3D80o-d4bQQwtN85M/edit

Chat about REST API here https://pa165.hipchat.com/chat/room/1740885

**Comment by brrossi** [comment]
I have sent an invitation to the preliminary blueprint on apiary (https://app.apiary.io/pa165)
Some discussions on methods of the facade layer, as I was putting down the design (https://pa165.hipchat.com/chat/room/1740885)
